### ISSUE TITLE
Project: Scraping Player Ratings of FUT players

### ISSUE THREAD

**Issue by HashirZahir** [zadevchat/ping#1]
Hi guys! I'm a newbie to GitHub and [this](https://github.com/HashirZahir/FIFA-Player-Ratings) was my first project. I'm not sure if you guys follow FIFA (the game), but I just wanted to share my project. Basicaly, it scrapes data from a website to obtain the EA ratings of players such as Messi, Ronaldo, etc (it can scrape the entire database). It could be useful for someone looking to model football based on these detailed ratings. If you have any comments please tell me! Thanks.

**Comment by kennethkalmer** [comment]
Well done! Please let me know what your Twitter handle is so I can mention you in a social blast :)

**Comment by HashirZahir** [comment]
Sure! My twitter handle is @hashbrownpower

**Comment by kennethkalmer** [comment]
Queued up a tweet for you later today!
